import { Header, Footer, JsonLd } from '../components';
import { site, staffingOffer, leadQuestions, staffingFitNote } from '../data';
export const metadata = { title: `Contact ${site.brand}`, description: 'Share the role, tasks, tools, schedule, and review needs for a virtual assistant staffing request.' };
export default function Contact() {
 const siteAny = site as any;
 const siteUrl = siteAny.url || `https://${String(site.domain).toLowerCase()}`;
 const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'ContactPage', name: `Contact ${site.brand}`, url: `${siteUrl}/contact` }, { '@type': 'Organization', name: site.brand, url: siteUrl }, { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Contact', item: `${siteUrl}/contact` }] }] };
 return <><Header/><main className="section"><JsonLd data={schema} /><div className="container two"><div><p className="eyebrow">Staffing intake</p><h1>Map the virtual assistant role you need</h1><p className="lead">Tell us what keeps landing back on your desk. Your answers give a staffing partner enough detail to review the role, tools, schedule, and owner-only decisions.</p><div className="card"><h2>What this intake covers</h2><ul className="list">{staffingOffer.included.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="card"><h2>Details worth adding</h2><ul className="list">{leadQuestions.map((q)=><li key={q}>{q}</li>)}</ul></div><p className="callout"><b>Fit depends on the work:</b>{' '}{staffingFitNote}</p></div><form className="card" action="/thank-you"><label>Name<br/><input required name="name" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Email<br/><input required name="email" type="email" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>Company / website<br/><input name="company" style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What role or work do you want staffed?<br/><textarea name="tasks" rows={6} style={{width:'100%', padding:12, margin:'6px 0 14px'}}/></label><label>What matters most?<br/><select name="concern" style={{width:'100%', padding:12, margin:'6px 0 14px'}}><option>Finding the right offshore staff</option><option>Quality checks and reporting</option><option>Coverage, schedule, and time zone</option><option>Tool access and data safety</option><option>Adding more than one role</option></select></label><button className="btn" type="submit">Review my role notes</button></form></div></main><Footer/></>;
}
