import { Header, Footer, CTA, JsonLd } from '../components';
import { comparisonRows, providerQuestions, site } from '../data';

export const metadata = { title: 'Compare the best virtual assistant services', description: 'Compare freelance VAs, managed VA services, specialist agencies, and employees before you hire.' };

export default function ComparePage(){
  const schema = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Compare virtual assistant services', url: `${site.url}/compare`, hasPart: { '@type': 'ItemList', itemListElement: comparisonRows.map((r, i) => ({ '@type': 'ListItem', position: i + 1, name: r.option, description: r.bestFor })) } };
  return <><Header/><main className="section"><JsonLd data={schema}/><div className="container"><p className="eyebrow">Compare</p><h1>Compare virtual assistant service options</h1><p className="lead">The best VA service is the one that fits your work, risk, and review time. Use this page to narrow the choice before a sales call.</p><div className="table"><div className="row"><b>Option</b><b>Best for</b><b>Ask this first</b></div>{comparisonRows.map((r)=><div className="row" key={r.option}><span>{r.option}</span><span>{r.bestFor}</span><span>{r.ask}</span></div>)}</div></div><section className="section"><div className="container two"><div><h2>How to pick</h2><p>Choose a freelance VA when you can train and manage the work yourself. Choose a managed service when replacement help, backup, and weekly quality checks matter. Choose a specialist agency when the work touches customers, records, support tickets, sales tools, or regulated admin.</p><p>Do not compare only rate cards. Compare the full support model: recruiting, training, management, backup, tool access, and how fast mistakes are fixed.</p></div><div className="card"><h3>Sales-call questions</h3><ul className="list">{providerQuestions.slice(0,5).map((q)=><li key={q}>{q}</li>)}</ul></div></div></section><CTA/></main><Footer/></>;
}
