import * as data from './data';
const dataAny = data as any;
const site = dataAny.site || {};
const domain = site.domain || 'this site';
const year = new Date().getFullYear();
export function JsonLd({data}:{data: any}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(data)}} />}
export function LogoMark(){return <span className="logo-mark-wrap"><img className="logo-img" src="/logo.svg" alt="" aria-hidden="true"/><span className="logo-name">{site.brand || domain}</span></span>}
export function Header(){return <header className="nav"><div className="nav-inner"><a className="logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><nav className="links" aria-label="Main navigation"><a href="/#models">Service models</a><a href="/compare">Compare</a><a href="/provider-vetting">Vetting guide</a><a href="/blog">Research</a></nav><a className="btn nav-cta" href="/contact">Build my shortlist</a></div></header>}
export function Footer(){return <footer className="footer legit-footer"><div className="footer-grid"><div className="footer-brand"><a className="footer-logo" href="/" aria-label={`${site.brand || domain} home`}><LogoMark/></a><p>{site.brand || domain} is a practical buyer's guide to virtual assistant service models, role scope, onboarding, and provider vetting.</p><p className="footer-note">We recruit and hire talent only in the Philippines. This is an independent informational website. If you submit a request, we may route it to a staffing team or service partner that can follow up.</p></div><div><h3>Explore</h3><div className="footer-links"><a href="/compare">Compare service models</a><a href="/provider-vetting">Provider vetting guide</a><a href="/blog/virtual-assistant-planning">Budget planning guide</a><a href="/blog/tasks-to-delegate-first">First tasks to delegate</a><a href="/blog/virtual-assistant-vs-employee">VA or employee?</a><a href="/blog">All research</a></div></div><div><h3>Company</h3><div className="footer-links"><a href="/contact">Contact</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms & Conditions</a><a href="/cancellation-policy">Cancellation Policy</a></div></div></div><div className="footer-bottom"><span>© {year} {site.brand || domain}. All rights reserved.</span><span>{domain}</span></div></footer>}
export function CTA(){return <section className="final-cta"><p className="eyebrow">Before you hire</p><h2>Write down the role first.</h2><p>Share the work, tools, schedule, and review needs. A staffing partner can use those details to check the fit.</p><a className="btn primary" href="/contact">Map my role</a></section>}
