export type FleetService = { slug: string; title: string; desc: string; tasks: readonly string[]; controls: readonly string[]; firstWeek: readonly string[] };
export type ResearchPost = { slug: string; title: string; excerpt: string; published: string; sections: readonly { heading: string; body: string }[]; sources?: readonly { name: string; url: string }[] };

export const fleetServices: readonly FleetService[] = [
  { slug: 'executive-calendar-management', title: 'Executive Calendar Management', desc: 'Build a Philippines-based executive calendar management workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'inbox-and-correspondence-support', title: 'Inbox and Correspondence Support', desc: 'Build a Philippines-based inbox and correspondence support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'travel-planning-assistance', title: 'Travel Planning Assistance', desc: 'Build a Philippines-based travel planning assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'crm-administration', title: 'CRM Administration', desc: 'Build a Philippines-based crm administration workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'sales-pipeline-support', title: 'Sales Pipeline Support', desc: 'Build a Philippines-based sales pipeline support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'customer-inbox-support', title: 'Customer Inbox Support', desc: 'Build a Philippines-based customer inbox support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'ecommerce-operations-assistance', title: 'Ecommerce Operations Assistance', desc: 'Build a Philippines-based ecommerce operations assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'podcast-production-coordination', title: 'Podcast Production Coordination', desc: 'Build a Philippines-based podcast production coordination workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'real-estate-transaction-support', title: 'Real Estate Transaction Support', desc: 'Build a Philippines-based real estate transaction support workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] },
  { slug: 'legal-administrative-assistance', title: 'Legal Administrative Assistance', desc: 'Build a Philippines-based legal administrative assistance workflow with documented responsibilities, access limits, and manager review.', tasks: ['Document the recurring virtual assistant work', 'Complete approved tasks in the client workflow', 'Record exceptions and next actions'], controls: ['Use named accounts and limited permissions', 'Follow written approval and escalation rules', 'Review work with a client-side owner'], firstWeek: ['Confirm scope and working hours', 'Practice with representative examples', 'Review the first completed work together'] }
];

// Add reviewed, source-backed original research here. The templates and sitemap update automatically.
export const researchPosts: readonly ResearchPost[] = [];
export const postsPerPage = 20;
