import { Header, Footer, CTA, JsonLd } from './components';
import { site, roles, industries, stats, blogPosts, comparisonRows, vettingSteps, providerQuestions, faqs, sourcePlaceholders, reviewCriteria, homepageImages, shortlistCards, stealthOffer, leadQuestions, staffingProcess, staffingFitNote } from './data';

export default function Home() {
  const schema = [{
    '@context': 'https://schema.org', '@type': 'WebPage', '@id': `${site.url}/#webpage`, url: site.url, name: `${site.brand} | Compare virtual assistant services`,
    description: 'Plain-English virtual assistant service comparisons, role-scope guides, vetting steps, and hiring checklists.',
    mainEntity: { '@type': 'ItemList', itemListElement: ['Compare VA services', 'Role-scope guide', 'Provider vetting checklist', 'Hiring guides'].map((name, i) => ({ '@type': 'ListItem', position: i + 1, name })) }
  }, {
    '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } }))
  }];
  return <><Header/><main>
    <JsonLd data={schema}/>
    <section className="hero"><div className="container grid"><div><p className="eyebrow">independent VA service reviews</p><h1>Find the right assistant service without guessing.</h1><p className="lead">Compare VA service types, role scope, risks, and first-week setup in plain English.</p><p>This site is for business owners who need help, but do not want a messy hire. Start with a clear task list, ask better provider questions, and test the work before you scale.</p><div style={{display:'flex', gap:12, flexWrap:'wrap', marginTop:22}}><a className="btn" href="/contact">Build my assistant plan</a><a className="btn secondary" href="/compare">Compare service types</a></div><div className="rating-strip" aria-label="Review factors"><span>★★★★★</span><b>Score before you sign</b><span>role scope</span><span>backup</span><span>security</span></div></div><div className="review-visual card"><img src={homepageImages.hero.url} alt={homepageImages.hero.alt}/><div className="award-card"><span className="award-badge">2026 shortlist lab</span><h3>Best first assistant tasks</h3><ul className="list"><li>Inbox sorting and calendar cleanup</li><li>Lead follow-up and CRM updates</li><li>Call answering and appointment setting</li><li>Customer support replies</li></ul><p className="quote">"Start small, measure weekly, then add more work."</p></div></div></div></section>
    <section className="section" id="services"><div className="container"><p className="eyebrow">Services</p><h2>Assistant roles people compare most</h2><div className="cards">{roles.map((r)=><div className="card" key={r}><h3>{r}</h3><p>Good for repeatable work with a clear checklist, tool access, examples, and owner review.</p><span className="pill">SOP ready</span><span className="pill">Remote friendly</span></div>)}</div></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">Who it helps</p><h2>Built for teams that need help but do not want a messy hire.</h2><p>Plain comparisons and checklists for picking the best VA service for each role.</p><p>We focus on job scopes, screening questions, training assets, time-zone fit, security basics, and weekly scorecards.</p><a className="btn secondary" href="/provider-vetting">Use the vetting checklist</a></div><div className="card"><h3>Industry examples</h3>{industries.map((i)=><span className="pill" key={i}>{i}</span>)}<p style={{marginTop:14}}>Each industry needs different access rules. A legal admin assistant, healthcare admin assistant, and ecommerce support assistant should not have the same permissions.</p></div></div></section>
        <section className="section review-section"><div className="container two"><div><p className="eyebrow">Editorial scorecard</p><h2>How we would grade a VA provider before a call</h2><p>Most provider pages look similar. The useful test is whether they can explain the role, protect your accounts, and fix a bad match without drama.</p><div className="score-list">{reviewCriteria.map((item)=><div className="score-row" key={item.label}><b>{item.score}</b><span><strong>{item.label}</strong><small>{item.note}</small></span></div>)}</div><p style={{marginTop:18}}><a className="btn" href="/provider-vetting">Open the vetting checklist</a></p></div><div className="image-card"><img src={homepageImages.scorecard.url} alt={homepageImages.scorecard.alt}/><div className="score-stamp"><span>4.7</span><b>review-ready score</b><small>Use after a small paid pilot, not before proof.</small></div></div></div></section>
    <section className="section shortlist-section"><div className="container"><p className="eyebrow">Shortlist lab</p><h2>Three service types worth comparing first</h2><p className="lead">A good ranking should say who the service fits, what can go wrong, and what proof to ask for before you sign.</p><div className="shortlist-grid"><div className="image-card editorial-photo"><img src={homepageImages.comparisonDesk.url} alt={homepageImages.comparisonDesk.alt}/><div className="score-stamp gold"><span>2026</span><b>review desk</b><small>Score the fit before the price.</small></div></div>{shortlistCards.map((card)=><a className="card shortlist-card" href={card.href} key={card.title}><div className="shortlist-top"><span className="rank-pill">{card.rank}</span><span className="stars">★★★★★ <b>{card.score}</b></span></div><h3>{card.title}</h3><p>{card.fit}</p><small>{card.proof}</small></a>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Comparison</p><h2>Four ways to hire assistant support</h2><div className="table"><div className="row"><b>Option</b><b>Best for</b><b>Ask this first</b></div>{comparisonRows.map((r)=><div className="row" key={r.option}><span>{r.option}</span><span>{r.bestFor}</span><span>{r.ask}</span></div>)}</div><p style={{marginTop:18}}><a className="btn secondary" href="/compare">Read the full comparison</a></p></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Vetting path</p><h2>A simple provider check before you sign</h2><div className="cards">{vettingSteps.map((s, i)=><div className="card" key={s.title}><span className="pill">Step {i+1}</span><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">Questions</p><h2>Ask better questions on sales calls</h2><ul className="list">{providerQuestions.map((q)=><li key={q}>{q}</li>)}</ul></div><div className="card"><h3>Red flag</h3><p>If a provider promises a perfect assistant without asking about your tasks, tools, access rules, or review process, slow down. Good matching starts with clear work.</p><a className="btn" href="/contact">Get a plan</a></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Guides</p><h2>Start with these hiring guides</h2><div className="cards">{blogPosts.slice(0,3).map((p)=><a className="card" href={`/blog/${p.slug}`} key={p.slug}><h3>{p.title}</h3><p>{p.excerpt}</p><span className="pill">{p.minutes} min read</span></a>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">FAQ</p><h2>Common questions</h2><div className="cards">{faqs.map((f)=><div className="card" key={f.q}><h3>{f.q}</h3><p>{f.a}</p></div>)}</div></div></section>

    <section className="section stealth-offer" id="process"><div className="container two"><div><p className="eyebrow">Stealth Agents staffing offer</p><h2>Built to turn this search into a real staffing plan.</h2><p className="lead">{stealthOffer.promise}</p><p>This site goes deeper than a thin directory. It helps you decide what to delegate, what to keep in-house, and how Stealth Agents can help you build a managed offshore staffing setup with clear roles and quality checks.</p><div className="quote">"Bring the task list. We help shape it into the right remote role before you hire."</div></div><div className="card"><h3>What the lead call should cover</h3><ul className="list">{leadQuestions.map((q)=><li key={q}>{q}</li>)}</ul><a className="btn" href="/contact">Request a staffing plan</a></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">What you get help with</p><h2>More than a name on a spreadsheet.</h2><p className="lead">A good offshore staffing offer should help with the role, the person, and the management rhythm after launch.</p><div className="cards">{stealthOffer.included.map((item)=><div className="card" key={item}><h3>{item}</h3><p>Use this as a check before you hire. The goal is simple: remove work from your team without creating a new management mess.</p></div>)}</div></div></section>
    <section className="section" id="compare"><div className="container"><p className="eyebrow">Staffing workflow</p><h2>A clear path from task list to trained support.</h2><div className="cards">{staffingProcess.map((step)=><div className="card stat" key={step.step}><h3>{step.step}</h3><b>{step.title}</b><p>{step.body}</p></div>)}</div><div className="callout"><b>Custom staffing fit:</b> {staffingFitNote}</div></div></section>
    <CTA />
  </main><Footer/></>;
}
