import { Header, Footer, CTA, JsonLd } from './components';
import { site, roles, industries, stats, blogPosts, comparisonRows, vettingSteps, providerQuestions, faqs, sourcePlaceholders } from './data';

export default function Home() {
  const schema = [{
    '@context': 'https://schema.org', '@type': 'WebPage', '@id': `${site.url}/#webpage`, url: site.url, name: `${site.brand} | Compare virtual assistant services`,
    description: 'Plain-English virtual assistant service comparisons, pricing guides, vetting steps, and hiring checklists.',
    mainEntity: { '@type': 'ItemList', itemListElement: ['Compare VA services', 'Pricing guide', 'Provider vetting checklist', 'Hiring guides'].map((name, i) => ({ '@type': 'ListItem', position: i + 1, name })) }
  }, {
    '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } }))
  }];
  return <><Header/><main>
    <JsonLd data={schema}/>
    <section className="hero"><div className="container grid"><div><p className="eyebrow">best virtual assistant services</p><h1>Find the right assistant service without guessing.</h1><p className="lead">Compare VA service types, pricing, risks, and first-week setup in plain English.</p><p>This site is for business owners who need help, but do not want a messy hire. Start with a clear task list, ask better provider questions, and test the work before you scale.</p><div style={{display:'flex', gap:12, flexWrap:'wrap', marginTop:22}}><a className="btn" href="/contact">Build my assistant plan</a><a className="btn secondary" href="/compare">Compare service types</a></div></div><div className="card"><h3>Best first assistant tasks</h3><ul className="list"><li>Inbox sorting and calendar cleanup</li><li>Lead follow-up and CRM updates</li><li>Call answering and appointment setting</li><li>Customer support replies</li><li>Simple reports, research, and admin</li></ul><p className="quote">“Start small, measure weekly, then add more work.”</p></div></div></section>
    <section className="section" id="services"><div className="container"><p className="eyebrow">Services</p><h2>Assistant roles people compare most</h2><div className="cards">{roles.map((r)=><div className="card" key={r}><h3>{r}</h3><p>Good for repeatable work with a clear checklist, tool access, examples, and owner review.</p><span className="pill">SOP ready</span><span className="pill">Remote friendly</span></div>)}</div></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">Who it helps</p><h2>Built for teams that need help but do not want a messy hire.</h2><p>Plain comparisons and checklists for picking the best VA service for each role.</p><p>We focus on job scopes, screening questions, training assets, time-zone fit, security basics, and weekly scorecards.</p><a className="btn secondary" href="/provider-vetting">Use the vetting checklist</a></div><div className="card"><h3>Industry examples</h3>{industries.map((i)=><span className="pill" key={i}>{i}</span>)}<p style={{marginTop:14}}>Each industry needs different access rules. A legal admin assistant, healthcare admin assistant, and ecommerce support assistant should not have the same permissions.</p></div></div></section>
    <section className="section" id="pricing"><div className="container"><p className="eyebrow">Costs and timing</p><h2>Realistic ranges before you talk to providers</h2><div className="cards">{stats.map((s)=><div className="card stat" key={s.label}><h3>{s.value}</h3><b>{s.label}</b><p>{s.note}</p></div>)}</div><p className="source-note">Source placeholders: {sourcePlaceholders.map((s)=><a key={s.name} href={s.url}> {s.name}</a>)}</p></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Comparison</p><h2>Four ways to hire assistant support</h2><div className="table"><div className="row"><b>Option</b><b>Best for</b><b>Ask this first</b></div>{comparisonRows.map((r)=><div className="row" key={r.option}><span>{r.option}</span><span>{r.bestFor}</span><span>{r.ask}</span></div>)}</div><p style={{marginTop:18}}><a className="btn secondary" href="/compare">Read the full comparison</a></p></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Vetting path</p><h2>A simple provider check before you sign</h2><div className="cards">{vettingSteps.map((s, i)=><div className="card" key={s.title}><span className="pill">Step {i+1}</span><h3>{s.title}</h3><p>{s.text}</p></div>)}</div></div></section>
    <section className="section"><div className="container two"><div><p className="eyebrow">Questions</p><h2>Ask better questions on sales calls</h2><ul className="list">{providerQuestions.map((q)=><li key={q}>{q}</li>)}</ul></div><div className="card"><h3>Red flag</h3><p>If a provider promises a perfect assistant without asking about your tasks, tools, access rules, or review process, slow down. Good matching starts with clear work.</p><a className="btn" href="/contact">Get a plan</a></div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">Guides</p><h2>Start with these hiring guides</h2><div className="cards">{blogPosts.slice(0,3).map((p)=><a className="card" href={`/blog/${p.slug}`} key={p.slug}><h3>{p.title}</h3><p>{p.excerpt}</p><span className="pill">{p.minutes} min read</span></a>)}</div></div></section>
    <section className="section"><div className="container"><p className="eyebrow">FAQ</p><h2>Common questions</h2><div className="cards">{faqs.map((f)=><div className="card" key={f.q}><h3>{f.q}</h3><p>{f.a}</p></div>)}</div></div></section>
    <CTA />
  </main><Footer/></>;
}
