#!/usr/bin/env python3
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-09-25"
base_source = (ROOT / "scripts" / "create_sep18_research_batch.py").read_text(encoding="utf-8")
namespace = {"__file__": str(ROOT / "scripts" / "create_sep18_research_batch.py")}
exec(base_source.split("\nentries = []", 1)[0], namespace)
namespace["DATE"] = DATE

TOPICS = [
 {"slug":"virtual-assistant-delegated-mailbox-authentication-study","title":"How Should Buyers Control Authentication for a Delegated Virtual Assistant Mailbox?","excerpt":"A buyer framework for mailbox delegation, identity, recovery, logging, and least-privilege access without shared passwords.","focus":"delegated mailbox authentication for virtual assistant services","question":"how a buyer can give a virtual assistant useful mailbox access while preserving individual identity, recoverability, review, and least privilege","decision":"whether the mailbox design supports the required work without relying on shared credentials or untraceable authority","unit":"one mailbox action mapped to named identity, permission, business purpose, approval boundary, audit record, recovery route, and access-removal event","scenario":"A buyer wants an assistant to triage a founder inbox, draft replies, and schedule follow-ups. Sharing the founder's password makes activity difficult to attribute and can widen access to account recovery, files, contacts, or connected services. A named delegated account can separate routine work from the owner's retained authority.","evidence":"Ask the provider and system owner to demonstrate the exact delegated permissions, authentication method, session controls, logs, recovery owner, and removal procedure in a test account. Verify that the assistant can perform allowed work and cannot change security settings, export unrelated data, or send high-consequence messages without approval.","limits":"A permission screen does not prove that day-to-day behavior follows the rule, and platform capabilities vary. Logs may be incomplete or retained for a limited period. The design needs periodic review, incident exercises, and an owner who can revoke access promptly.","finding":"Mailbox access is decision-grade when every assistant uses an attributable identity and the buyer can demonstrate allowed actions, prohibited actions, recovery, and revocation.","image":"/blog/images/virtual-assistant-email-security-controls.webp"},
 {"slug":"virtual-assistant-customer-complaint-authority-study","title":"Where Should a Virtual Assistant's Authority End in Customer Complaint Handling?","excerpt":"A scenario-based method for defining response, remedy, escalation, and evidence boundaries in customer complaint workflows.","focus":"virtual assistant customer complaint authority","question":"where a buyer should place the decision boundary when a virtual assistant receives, documents, and responds to customer complaints","decision":"which complaint actions can be delegated, which require approval, and which conditions must stop the workflow","unit":"one complaint mapped to customer request, known facts, sensitivity, allowed response, prohibited commitment, remedy ceiling, escalation trigger, owner, and retained evidence","scenario":"An assistant can acknowledge a late delivery and gather facts, but a complaint may also allege discrimination, threaten legal action, request a refund beyond policy, or reveal sensitive information. A friendly reply template does not define when the assistant must stop or who owns the next decision.","evidence":"Build a scenario set covering an ordinary service miss, missing information, repeated complaint, policy exception, safety concern, legal threat, and sensitive-data disclosure. Require the provider to show the permitted action, exact escalation trigger, response clock, named owner, and record created for each case.","limits":"Complaint severity is contextual, and customers may reveal decisive facts late in a conversation. Scripts cannot replace qualified legal, safety, or management review. A small test supports a bounded delegation choice but cannot predict every customer interaction.","finding":"Complaint support is safely delegated only when acknowledgment and fact gathering are separated from remedies, admissions, policy exceptions, and other decisions the buyer retains.","image":"/blog/images/virtual-assistant-customer-escalation-notes.webp"},
 {"slug":"virtual-assistant-ai-tool-disclosure-study","title":"What Should Buyers Ask About AI Tools Used by a Virtual Assistant Service?","excerpt":"A practical evidence framework for tool disclosure, data boundaries, human review, output risk, and change control.","focus":"AI tool use in virtual assistant services","question":"what a buyer should verify when a virtual assistant or provider may use an AI-enabled tool in delegated work","decision":"whether a named tool and use case fit the task, information boundary, review requirement, and buyer's tolerance for error","unit":"one AI-assisted task mapped to tool, input, data category, configuration, output use, human reviewer, prohibited use, retention assumption, and change owner","scenario":"A provider proposes using an AI writing feature to summarize customer conversations. The feature may save time, but the buyer does not yet know which data leaves the primary system, whether content trains a model, who checks omissions, or how a silent product change would be reviewed.","evidence":"Request a current tool register and walk through one ordinary, ambiguous, and prohibited case. Record the vendor and feature, approved inputs, excluded data, account configuration, retention information, reviewer, correction path, and notification rule when the tool or purpose changes. Test the final output against the original record.","limits":"Vendor terms, models, and integrations can change, and public documentation may not describe every configuration. Human review can also become superficial when outputs appear fluent. The method does not certify a tool or resolve applicable legal duties; it exposes assumptions for accountable review.","finding":"AI use becomes reviewable when the service names the tool and purpose, restricts inputs, preserves human accountability, tests material errors, and treats tool changes as role changes.","image":"/blog/images/virtual-assistant-content-fact-checking.webp"},
 {"slug":"virtual-assistant-holiday-coverage-evidence-study","title":"What Evidence Supports a Virtual Assistant Holiday Coverage Promise?","excerpt":"A buyer method for testing calendars, service windows, backups, handoffs, access, and recovery across holiday periods.","focus":"virtual assistant holiday coverage evidence","question":"what evidence a buyer should request before relying on a virtual assistant provider's holiday or absence coverage promise","decision":"whether the proposed coverage preserves the buyer's critical service window without unsafe access expansion or hidden owner work","unit":"one coverage period mapped to applicable calendar, required service window, primary role, backup role, handoff artifact, access state, escalation owner, test result, and recovery plan","scenario":"A buyer needs weekday inbox monitoring while the assistant and buyer operate under different holiday calendars. The provider says coverage is included, but has not named the backup, demonstrated access, defined which tasks continue, or explained who notices when a handoff fails.","evidence":"Compare the buyer, assistant, provider, and customer calendars for the actual service period. Select one ordinary holiday and one short-notice absence, then test notification, handoff, backup access, queue ownership, approval limits, and return-to-primary steps. Record the gap rather than assuming every local holiday is equivalent.","limits":"A scheduled exercise cannot reproduce illness, severe weather, connectivity loss, or simultaneous absences. Holiday rules and business priorities can change. Coverage evidence should therefore show both a tested path and a named owner who can make a live priority decision.","finding":"A coverage promise is credible only when dates, service windows, named roles, permissions, handoff evidence, and recovery have been tested against the buyer's real queue.","image":"/blog/images/virtual-assistant-backup-coverage-plan.webp"},
 {"slug":"virtual-assistant-financial-approval-boundary-study","title":"How Should Buyers Set Financial Approval Boundaries for a Virtual Assistant?","excerpt":"A control framework for preparing transactions while retaining authorization, verification, exception, and audit decisions.","focus":"virtual assistant financial approval boundaries","question":"how a buyer can delegate financial administration without silently delegating authorization or exception decisions","decision":"which preparation and reconciliation steps an assistant may perform and which payment, refund, vendor-change, or exception actions remain with an authorized owner","unit":"one financial action mapped to source evidence, system permission, preparer, verifier, approver, amount or risk threshold, exception, log, and reversal route","scenario":"An assistant prepares invoices and vendor payments, then receives an email changing bank details shortly before a deadline. Efficiency pressure can blur the line between entering information and authorizing value transfer. A monetary limit alone does not address identity verification or changed instructions.","evidence":"Map each step from request through reconciliation and assign separate preparer, verifier, and approver roles where risk warrants it. Test a normal item, duplicate, changed bank detail, missing evidence, urgent request, and out-of-policy refund. Verify technical permissions rather than relying only on written instructions.","limits":"Controls must match transaction size, frequency, systems, staffing, and applicable duties. Small teams may not achieve full separation and will need explicit compensating review. This operational research is not accounting, banking, tax, or legal advice.","finding":"Financial administration is delegable when preparation is distinct from authorization and every exception has independent verification, an accountable approver, and a recoverable record.","image":"/blog/images/virtual-assistant-invoice-processing-controls.webp"}
]

entries=[]
for topic in TOPICS:
    path=ROOT/"content"/"research"/f'{topic["slug"]}.mdx'
    if path.exists(): raise SystemExit(f"refusing to overwrite {path}")
    text=namespace["body"](topic).replace("September 18, 2026","September 25, 2026")
    path.write_text(text,encoding="utf-8")
    entries.append({"family":"research","topic":topic["title"],"slug":topic["slug"],"sourcePaths":[str(path.relative_to(ROOT))],"sourceTitles":[s[0] for s in namespace["SOURCES"]],"sourcePublishers":[s[1] for s in namespace["SOURCES"]],"sources":[s[2] for s in namespace["SOURCES"]],"checkedDate":DATE,"publishedAt":DATE,"contentHash":hashlib.sha256(text.encode()).hexdigest(),"liveUrl":f'https://bestvirtualassistantservices.com/research/{topic["slug"]}',"commitSha":None,"deploymentEvidence":"Research staged locally for the combined 12 Blog + 5 Research release; Blog integrator and browser operator own the single production push, deployment, and public route verification.","verificationTime":None,"status":"staged-for-combined-release"})

manifest_path=ROOT/".paperclip"/"daily-content"/DATE/"research.json"
manifest_path.parent.mkdir(parents=True,exist_ok=True)
manifest_path.write_text(json.dumps({"runDate":DATE,"cycleLabel":"September 25, 2026 recovery cycle","family":"research","requiredCount":5,"stagedCount":5,"verifiedCount":0,"timezone":"site configured local timezone; final date must be reconciled by integrator to each article's first successful public verification date","repository":"coolifystealthagents/bestvirtualassistantservices","productionBranch":"main","combinedReleaseRequired":True,"researchMayPushOrDeploy":False,"baseProductionSha":"190aa4017c74ba6d1441d391d59502e13d28446a","entries":entries},indent=2)+"\n",encoding="utf-8")
print("created exactly 5 net-new research articles and combined-release handoff manifest")
