from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
DATE = '2026-08-23'

ARTICLES = [
    ('virtual-assistant-article-reader-scenario-test', 'Test a Virtual Assistant Services Article With Reader Scenarios', 'A reader scenario test shows whether a virtual assistant services article helps someone make a real delegation decision.', 'A draft is ready for review only when its advice survives the questions a likely reader would ask at the moment of handoff.', 'reader scenarios', 'Imagine a manager deciding whether a recurring inbox task is ready to delegate. The reader does not need a polished slogan. They need to know what information to collect, what the assistant may prepare, and which judgment stays with the manager.'),
    ('virtual-assistant-blog-claim-strength-ladder', 'Use a Claim Strength Ladder in Virtual Assistant Services Writing', 'A claim strength ladder helps article teams match wording to the evidence available for a virtual assistant services question.', 'Public guidance becomes safer when each sentence is written at the strongest level the source material can actually support.', 'claim strength', 'A sentence about a virtual assistant workflow can describe a method, report an observation, or promise an outcome. Those are different jobs. A claim ladder gives the reviewer a way to lower the wording when the evidence is thinner than the draft suggests.'),
    ('virtual-assistant-daily-article-intent-register', 'Keep an Intent Register for Daily Virtual Assistant Articles', 'An intent register records the reader decision behind each daily article so a busy queue does not drift into disconnected topics.', 'The article queue should preserve why a topic exists, what decision it supports, and when that purpose is no longer useful.', 'intent register', 'A title can look relevant while serving no clear reader decision. An intent register keeps the article promise tied to a service question such as delegation readiness, escalation ownership, or review preparation.'),
    ('virtual-assistant-article-plain-language-pass', 'Run a Plain-Language Pass on Virtual Assistant Services Articles', 'A plain-language pass makes virtual assistant services guidance easier to act on without weakening its boundaries or caveats.', 'Plain language is a workflow check: replace vague process words with observable actions while keeping uncertainty visible.', 'plain-language editing', 'Readers comparing virtual assistant services often scan for the next action. If a sentence says to optimize coordination, the reader still has to guess what to do. A plain-language pass names the record, owner, timing, or question that makes the advice usable.'),
    ('virtual-assistant-blog-reference-snapshot', 'Create a Reference Snapshot for Virtual Assistant Blog Research', 'A reference snapshot records the exact source context used for a virtual assistant blog article before research notes become stale.', 'A snapshot should preserve the source identity, relevant passage, retrieval date, and claim it supports so later edits do not rely on memory.', 'reference snapshots', 'Research for a virtual assistant services article can change while the draft is in review. A compact snapshot lets an editor see what a source supported at the time of writing and which sentences need another look when the source is updated.'),
    ('virtual-assistant-content-brief-decision-owner', 'Name the Decision Owner in a Virtual Assistant Content Brief', 'A content brief works better when it names the person who can resolve scope, evidence, and publication questions.', 'A virtual assistant may prepare a brief, but the brief must identify who owns the public decision when reasonable people could choose different answers.', 'decision ownership', 'A brief that lists tasks but not decision ownership creates quiet delays. The assistant may gather examples, compare sources, and flag a risk, yet still lack authority to decide whether a claim belongs in public guidance.'),
    ('virtual-assistant-article-approval-window', 'Set an Approval Window for Virtual Assistant Services Articles', 'An approval window gives daily article work a clear review period without turning an unanswered message into automatic publication.', 'Time limits should create a visible escalation or hold state, never imply that silence proves public accuracy.', 'approval windows', 'Daily publishing creates pressure to treat review as a quick reply. A defined window can help a manager plan, but it must distinguish a missed response from an approval and show what happens to the article while the decision is pending.'),
    ('virtual-assistant-blog-coverage-gap-audit', 'Audit Coverage Gaps in a Virtual Assistant Services Blog', 'A coverage-gap audit finds important reader decisions that a virtual assistant services blog has not explained clearly.', 'Coverage is not a count of titles; it is a map of unanswered decisions, weak handoffs, and missing role boundaries.', 'coverage gaps', 'A blog can have many articles about hiring and still leave a buyer without guidance on access limits, quality review, or escalation. A gap audit starts with the decisions readers face and checks whether the library gives them a usable path.'),
    ('virtual-assistant-article-quote-permission-check', 'Add a Quote Permission Check to Virtual Assistant Blog Work', 'A quote permission check keeps a virtual assistant blog article from treating useful wording as automatically reusable public material.', 'Article research needs a separate check for whether a passage may be quoted, paraphrased, linked, or omitted.', 'quote permissions', 'A source can be relevant without being safe to copy. The person preparing an article should record what use is intended, what attribution is needed, and when a paraphrase would be clearer than a direct quotation.'),
    ('virtual-assistant-publishing-rollback-note', 'Write a Rollback Note for Virtual Assistant Article Publishing', 'A rollback note tells a virtual assistant publishing team what to restore if a newly released article needs to be withdrawn or corrected.', 'Rollback planning is a recordkeeping task that makes correction faster while keeping the approval owner in control of the public change.', 'rollback notes', 'A correction is harder when nobody remembers the prior title, source file, image, or approved wording. A rollback note captures the state that should be restored and the reason a reversal may be requested.'),
    ('virtual-assistant-content-calendar-sequence', 'Sequence a Virtual Assistant Services Content Calendar', 'A sequence turns a virtual assistant services content calendar into a learning path instead of a list of unrelated daily assignments.', 'Calendar order should follow reader decisions and dependencies, so each article prepares the question answered by the next one.', 'content sequence', 'Publishing a basic delegation guide before an escalation guide gives readers a place to start. Sequencing asks what a reader must understand first, which uncertainty follows, and where a later article can point back without repeating the earlier work.'),
    ('virtual-assistant-article-search-snippet-review', 'Review Search Snippets for Virtual Assistant Services Articles', 'A search-snippet review checks whether an article summary accurately sets expectations for a virtual assistant services reader.', 'The snippet is part of the article promise and must remain faithful to the page instead of chasing attention with a broader claim.', 'snippet review', 'A reader may choose an article from its title and summary before seeing the body. If the snippet promises a provider comparison but the page explains a delegation checklist, the first handoff has already failed.'),
]

SECTIONS = [
    ('Start with the decision, not the document', 'Write the reader decision in one sentence before opening the article file. In virtual assistant services work, that decision might concern what to delegate, what to verify, who should approve a change, or when to escalate an exception. A useful record names the decision, the person making it, and the information that could change the answer. This keeps the article from becoming a general essay about productivity. It also gives a reviewer something concrete to test. If the draft cannot say what the reader should be able to decide after reading, pause the assignment and narrow the brief.'),
    ('Separate preparation from authority', 'A virtual assistant can gather source material, organize a comparison, draft questions, and mark an uncertain passage. Those actions prepare a decision. They do not automatically transfer authority to publish a claim, approve a policy, or speak for a company. Put the boundary in the article as practical guidance. Say what the assistant may do, what the accountable owner must decide, and what evidence should accompany an escalation. This distinction protects both the reader and the operator when a workflow crosses from administration into judgment.'),
    ('Use a small record that can be inspected', 'The best control is often a short record that another person can understand without reconstructing the whole conversation. Capture the article promise, source or example used, open question, current owner, next action, and condition that would reopen the work. Keep hypothetical examples labeled as examples. Do not fill missing company facts with plausible details. A virtual assistant services article earns trust by showing where its guidance ends. The record also makes handoffs quicker when a reviewer returns a narrow correction instead of asking for a full restart.'),
    ('Walk the uncomfortable case', 'Test the guidance against a case that creates friction. The source may support a general method but not a strong outcome claim. A reviewer may be unavailable near the intended publishing time. The reader may ask for an exception that the article never addresses. Describe the point at which the normal path stops, then state the safe next move: narrow the wording, request evidence, hold the article, or route the decision. This is where a virtual assistant services guide becomes operational rather than decorative.'),
    ('Check the public boundary', 'Before release, read the article as a stranger who knows nothing about internal work. Remove invented locations, credentials, client results, testimonials, prices, rates, and guarantees. Avoid implying that a method produces a fixed business outcome. Keep the niche central by tying every example to virtual assistant roles, manager handoffs, service selection, quality review, or recurring administration. If a sentence only sounds impressive but does not help a reader choose or verify something, cut it. Plain, bounded advice is easier to maintain.'),
    ('Close with a handoff someone can act on', 'End with a next action that has an owner and a condition for reopening the question. The action may be to update a brief, attach a source, ask an accountable reviewer, or hold a release. A status such as “ready” is not enough unless the article defines what ready means. The handoff should preserve the reader decision, the evidence checked, and the unresolved limit. That detail lets a virtual assistant continue useful preparation without silently making the decision that belongs to the service owner.'),
]

def article(slug, title, excerpt, thesis, focus, angle, idx):
    order = list(range(len(SECTIONS)))
    shift = (idx * 2) % len(SECTIONS)
    order = order[shift:] + order[:shift]
    lines = ['---', f'slug: {slug}', f'title: {title}', f'excerpt: {excerpt}', f'publishedAt: {DATE}', f'updatedAt: {DATE}', 'category: Operations', 'tags: [virtual assistant, article creation, workflow]', f'featuredImage: /blog/images/{slug}.webp', f'heroImageAlt: {title}', 'readingTime: 10 minutes', 'relatedArticles: [virtual-assistant-outsourcing-readiness-checklist, virtual-assistant-provider-vetting-checklist, virtual-assistant-content-calendar-operations]', '---', f'# {title}', '', thesis + ' ' + angle]
    for n, section_idx in enumerate(order):
        heading, body = SECTIONS[section_idx]
        if n == 0:
            heading = f'{title}: {heading}'
        extra = f' For this {focus} question, record the exact phrase that needs review and the reason it matters to the reader. A manager should be able to tell whether the next move is preparation, approval, correction, or escalation. Keep that distinction visible when the work is handed to a virtual assistant.'
        if section_idx == 1:
            extra += f' The boundary is especially important for {focus}: preparation can be delegated, while a public judgment still needs an accountable owner.'
        if section_idx == 3:
            extra += f' In a {focus} review, the uncomfortable case is useful because it exposes the assumption the normal checklist leaves out.'
        lines += ['', f'## {heading}', '', body + extra]
    lines += ['', '## Questions before release', '', f'Can a reader explain the decision this {focus} guide supports? Does each example stay within the known evidence? Are the assistant preparation steps separated from owner approval? Does the article give a real correction or escalation path? Check the [virtual assistant services library](/services) and the [provider vetting guide](/provider-vetting) for adjacent planning questions. For security context, consult [NIST small business cybersecurity guidance](https://www.nist.gov/itl/smallbusinesscyber). If the answer to a release question is uncertain, hold the item and route it to the accountable owner.']
    return '\n'.join(lines) + '\n'

def main():
    blog = ROOT / 'content/blog'; blog.mkdir(parents=True, exist_ok=True)
    receipt_dir = ROOT / f'.paperclip/daily-content/{DATE}/prompts'; receipt_dir.mkdir(parents=True, exist_ok=True)
    entries = []
    for idx, item in enumerate(ARTICLES, 1):
        slug, title, excerpt, thesis, focus, angle = item
        (blog / f'{slug}.mdx').write_text(article(slug, title, excerpt, thesis, focus, angle, idx), encoding='utf-8')
        (receipt_dir / f'{slug}.txt').write_text(f'Gemini prompt receipt for /blog/{slug}\nEditorial illustration for a virtual assistant services article about {focus}; show a distinct work scene with documents, a review marker, and a clear handoff; navy, cream, and warm gold palette; landscape 1200x630; no logos, no text, no watermark, no identifiable people.\n', encoding='utf-8')
        entries.append({'slug': slug, 'route': f'/blog/{slug}', 'sourcePath': f'content/blog/{slug}.mdx', 'sourceDateField': 'publishedAt', 'sourceDate': DATE, 'renderedDate': DATE, 'renderedDateFields': ['datePublished', 'time[datetime]'], 'imagePath': f'public/blog/images/{slug}.webp', 'promptReceipt': f'.paperclip/daily-content/{DATE}/prompts/{slug}.txt', 'introducedByCommit': 'PENDING'})
    manifest = ROOT / f'.paperclip/daily-content/{DATE}/blog.json'; manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(json.dumps({'schemaVersion': 1, 'contract': 'fleet-aug23-blog-v7', 'family': 'blog', 'targetDate': DATE, 'minimum': 12, 'entries': entries}, indent=2) + '\n', encoding='utf-8')
    print(f'created {len(entries)} articles')

if __name__ == '__main__': main()
