from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
BLOG = ROOT / "content/blog"
DATE = "2026-08-18"
topics = [
    ("article-brief-acceptance", "How a Virtual Assistant Can Turn an Article Brief into an Acceptance Checklist", "article brief acceptance", "A brief is useful only when it tells a writer and reviewer what a finished article must accomplish. An acceptance checklist turns that intention into observable checks before drafting begins.", "Start with the reader's question, the decision the article should support, and the evidence that can answer it. Then define the required title angle, scope, examples, internal links, and review owner. A virtual assistant can turn those requirements into a short working sheet without pretending that a checklist proves the claims.", "The most important boundary is between preparation and editorial judgment. Administrative support can notice a missing source, duplicate angle, or unclear audience. The editor decides whether the thesis is accurate, useful, and appropriate for publication."),
    ("source-packet-for-bloggers", "A Source Packet Workflow for Virtual Assistant Blog Support", "source packet workflow", "A source packet gives an article writer a bounded set of material to understand before opening a blank document. It reduces hunting time while keeping the difference between evidence and interpretation visible.", "Record the question being researched, the source title, the relevant passage location, the date checked, and the limit of what the source establishes. Separate primary material from commentary and note unresolved conflicts rather than smoothing them over.", "A virtual assistant may gather and label sources, but the writer owns the argument. Do not turn a search result into a company fact or add a statistic merely because it sounds persuasive. The packet should make careful writing easier, not make unsupported certainty look organized."),
    ("blog-fact-check-handoff", "Designing a Fact-Check Handoff for Virtual Assistant Article Teams", "blog fact-check handoff", "Fact-checking works better as a handoff with named claims than as a vague request to review an entire article. Each claim needs a source, a status, and a person who can resolve uncertainty.", "Extract factual statements into a review list, preserve the surrounding sentence, and link each item to its supporting source. Mark opinion, recommendation, example, and fact differently so the reviewer spends attention where verification matters.", "The assistant can collect claims, trace links, and flag a mismatch. The subject owner or editor decides whether wording is supported. Never convert a missing source into a confident sentence or use a citation as permission to extend a claim beyond its evidence."),
    ("editorial-calendar-dependency-map", "Map Editorial Calendar Dependencies Before a Virtual Assistant Publishes", "editorial calendar dependencies", "An editorial calendar is more than a row of topics and dates. It is a dependency map showing which brief, source review, image, approval, and publishing detail must be ready before an article can move forward.", "For each article, list the reader question, draft owner, source packet, review stage, asset status, link destinations, and release decision. Use statuses that describe evidence, such as waiting for source review or ready for editorial review, rather than optimistic percentages.", "A virtual assistant can maintain the map and identify blockers. The editor retains decisions about claims, positioning, timing, and final release. A green calendar cell should never be treated as approval if the approving person has not recorded it."),
    ("article-update-trigger-register", "When Should a Virtual Assistant Flag an Article for Review?", "article update triggers", "An article should be reviewed when a meaningful part of its answer may no longer be reliable, not simply because a calendar reminder appeared. A trigger register makes that judgment easier to apply consistently.", "Track the claim, the reason for the trigger, the source that changed or became unavailable, the affected section, and the review owner. Useful triggers include a changed process, a broken reference, a newly discovered scope limit, or feedback that exposes ambiguity.", "Support staff can monitor links, record reader questions, and assemble a change brief. They should not silently rewrite an approved answer or decide that a material claim is still safe. The editor decides whether to revise, annotate, retire, or leave the article unchanged."),
    ("blog-duplicate-topic-triage", "A Duplicate-Topic Triage Method for Virtual Assistant Blog Planning", "duplicate topic triage", "Two titles can look different while answering the same reader question. Duplicate-topic triage compares intent, thesis, examples, and decision stage before a new article consumes drafting time.", "Read the existing title and opening, write its one-sentence promise, and compare that promise with the proposed article. Check whether the reader, operating problem, and recommended next step are genuinely different. Record a merge, redirect, narrow, or proceed decision.", "A virtual assistant can assemble the comparison and point out overlap. An editor decides whether two pieces should coexist. Do not solve duplication by changing only a noun in a title; the new article needs a different question and useful reasoning."),
    ("article-review-queue-aging", "How to Manage an Aging Article Review Queue with a Virtual Assistant", "article review queue aging", "An article review queue becomes risky when age is the only signal. A useful queue distinguishes waiting time from review effort, claim risk, and the cost of publishing an incomplete answer.", "Record when a draft entered review, its estimated reading load, open evidence questions, requested reviewer, and next decision. Group work by what is blocking it: unclear brief, source conflict, structural problem, or final copy review.", "The assistant can sort, remind, and prepare a concise status note. The editor decides which article to defer or advance. Do not report queue age as a quality result, and do not mark a draft complete because a reminder was sent."),
    ("content-brief-question-ladder", "Build a Reader Question Ladder for Every Virtual Assistant Article Brief", "reader question ladder", "A question ladder takes an article from a broad topic to the practical questions a reader must answer. It gives a virtual assistant a way to test whether a brief is specific enough to guide useful research.", "Write the broad concern, the operational decision, the constraints, the evidence needed, and the action the reader can take. Check that each rung narrows the next one instead of creating a list of unrelated subtopics.", "Support can organize the ladder and identify missing questions. The writer decides the central thesis and what to leave out. A ladder is a scope tool, not a promise to answer every possible question in one article."),
    ("blog-image-alt-text-register", "An Accessible Image Alt-Text Register for Virtual Assistant Blog Operations", "blog image alt text", "An image register protects a publishing routine from treating filenames as descriptions. It records what an image contributes to an article and whether the alt text communicates that purpose without inventing details.", "List the article, asset path, visual subject, functional purpose, draft alt text, reviewer, and approval state. If an image is decorative, say so in the working record rather than forcing a misleading description.", "A virtual assistant can inventory assets and flag missing or repetitive descriptions. Editorial and accessibility judgment remain with the responsible reviewer. Do not describe information that cannot be seen, and do not use alt text to insert keywords unrelated to the image."),
    ("internal-link-intent-map", "Create an Internal-Link Intent Map for Virtual Assistant Blog Articles", "internal link intent mapping", "Internal links are most useful when they help a reader take the next relevant step. An intent map ties each link to the question it answers instead of treating links as decoration added at the end.", "For every proposed link, record the source article, destination purpose, anchor meaning, and whether the destination actually supports the promised next step. Keep commercial, explanatory, and policy destinations distinct.", "A virtual assistant can inventory destinations and identify broken or mismatched links. The editor decides the final wording and relevance. Do not force a link into a sentence merely to meet a count, and do not imply that a destination proves a claim it does not address."),
    ("blog-readability-review-sheet", "A Readability Review Sheet a Virtual Assistant Can Prepare", "blog readability review", "Readability is not a score alone. A review sheet asks whether a busy reader can identify the problem, follow the reasoning, and find the boundary of the recommendation.", "Check paragraph purpose, heading sequence, unexplained terms, sentence load, lists, examples, and the distance between a claim and its qualification. Read the opening and conclusion separately to see whether they make the same promise.", "The assistant can mark friction and suggest questions for the editor. It should not flatten every article into one voice or remove necessary nuance to make a draft shorter. The editor protects meaning while improving access."),
    ("article-approval-evidence-log", "Keep an Article Approval Evidence Log with Virtual Assistant Support", "article approval evidence", "Approval is easier to trust when the record shows what was reviewed, by whom, against which version, and with what decision. An evidence log separates a real release decision from an informal comment.", "Record the article identifier, version, reviewer role, open issues, decision, date, and link to the reviewed copy. If approval is conditional, state the exact condition and do not let a later edit inherit it automatically.", "A virtual assistant can maintain version references and chase missing decisions. The accountable editor approves public wording. Never infer approval from silence, a completed task, or an older version of the same article."),
    ("blog-claim-risk-ranking", "Rank Article Claim Risk Before a Virtual Assistant Starts Research", "article claim risk ranking", "Not every sentence deserves the same research treatment. Claim-risk ranking helps an article team spend review effort on statements that could mislead readers or overstate what the evidence says.", "Classify claims by consequence, specificity, freshness, and whether they concern a regulated, sensitive, or changing area. Put high-risk claims at the top of the source plan and state what evidence would be sufficient before drafting.", "The assistant can apply the agreed labels and surface gaps. The editor or subject owner determines whether a claim is safe and how narrowly it should be worded. A risk label is a prompt for judgment, not an automatic publication decision."),
    ("blog-brief-version-control", "Simple Brief Version Control for Virtual Assistant Article Work", "brief version control", "A brief that changes without a visible history creates avoidable rework. Lightweight version control lets the writer and reviewer see which audience, thesis, sources, and constraints belong to the current draft.", "Give each brief a revision date, change note, owner, and current status. Preserve the prior thesis when a new one replaces it, and tell the writer which requirements were added, removed, or narrowed.", "A virtual assistant can maintain the register and compare versions. The editor owns the decision to change scope. Do not overwrite the only copy of an approved brief or assume that a revised title leaves the body requirements unchanged."),
    ("blog-comment-resolution-board", "Use a Comment-Resolution Board for Virtual Assistant Article Reviews", "comment resolution board", "Review comments become expensive when they live in several places or lack an owner. A resolution board turns feedback into a finite set of decisions without encouraging mechanical acceptance of every suggestion.", "Capture the quoted issue, section, comment type, proposed response, owner, status, and final rationale. Separate factual corrections, clarity requests, scope questions, and preference disagreements.", "The assistant can consolidate comments and identify duplicates. The editor decides which changes preserve the article's purpose. Do not treat a comment count as a quality measure or close a disagreement without recording who resolved it."),
    ("blog-refresh-scope-brief", "Write a Refresh-Scope Brief Before Updating an Existing Virtual Assistant Article", "refresh scope brief", "An update should begin with a map of what changed and what must remain stable. A refresh-scope brief prevents a small correction from becoming an unreviewed rewrite of the article's entire promise.", "List the trigger, affected claims, sources to revisit, sections likely to change, links to retest, and the reviewer needed. Mark untouched sections explicitly so the change boundary is understandable.", "A virtual assistant can compare versions and assemble evidence. The editor decides whether the article needs a narrow correction or a new piece. Do not change publication dates or wording simply to make an old article appear current."),
    ("blog-editorial-exception-register", "An Editorial Exception Register for Virtual Assistant Publishing Routines", "editorial exception register", "A publishing routine needs a safe place for unusual cases. An exception register records why a normal check could not be followed and who accepted the remaining risk.", "Record the article, failed or unavailable check, evidence reviewed, temporary decision, expiry or follow-up date, and approving role. Keep exceptions specific; a broad note such as quality reviewed does not explain what happened.", "The assistant can document and remind. The editor or designated owner accepts or rejects the exception. Never use an exception register to make a prohibited claim, skip a required approval, or turn a recurring failure into a permanent informal process."),
    ("blog-publishing-metadata-check", "A Metadata Checkpoint for Virtual Assistant Blog Publishing", "blog publishing metadata", "A polished article can still be hard to find or interpret when its metadata is incomplete or inconsistent. A metadata checkpoint gives the publishing owner a small, repeatable set of facts to verify.", "Check the title, description, publication date, canonical path, image reference, heading structure, and visible category against the approved record. Record the exact source value and the person who resolves a mismatch.", "A virtual assistant can compare fields and report discrepancies. The publishing owner decides the final metadata and release. Do not invent a date, keyword, result, or category merely to fill a blank."),
    ("blog-reader-feedback-routing", "Route Reader Feedback to the Right Virtual Assistant Article Owner", "reader feedback routing", "Reader feedback is valuable only when it reaches the person who can act on it. Routing separates a broken link from a factual concern, a usability issue, a service question, and a request outside the article's scope.", "Capture the article path, feedback date, reader's stated issue, exact location, urgency signal, and proposed owner. Preserve the original wording and avoid turning one comment into a general conclusion.", "A virtual assistant can classify, deduplicate, and prepare a response queue. The editor handles public corrections, while service owners handle operational questions. Do not promise a change or reveal private correspondence from a feedback record."),
    ("blog-topic-queue-decision-record", "Keep Topic-Queue Decisions Clear with Virtual Assistant Support", "topic queue decisions", "A topic queue should show why an idea is ready, deferred, narrowed, or declined. Recording the decision protects the calendar from repeatedly reopening the same unresolved question.", "For each idea, record reader intent, distinct angle, evidence available, related existing articles, likely owner, risks, and decision date. A deferred topic needs a condition for reconsideration rather than a vague maybe later label.", "The assistant can research overlap and maintain statuses. Editorial leadership chooses priorities and scope. Do not turn a queue into a promise to publish every idea or treat search demand as proof that an article is accurate or useful."),
    ("blog-draft-handoff-package", "What Belongs in a Virtual Assistant Blog Draft Handoff Package", "draft handoff package", "A draft handoff package lets a reviewer begin with context instead of reconstructing the writer's process. It should contain the article, its brief, its source notes, and the questions that remain open.", "Include the current draft link, thesis, audience, source list, unresolved claims, requested review type, internal links, image status, and due decision. Label suggestions separately from approved facts and keep obsolete versions out of the active handoff.", "The assistant can assemble the package and check completeness. The reviewer decides whether the draft meets its purpose. Never hide an unresolved source conflict because the handoff looks cleaner without it."),
    ("blog-month-end-quality-review", "A Month-End Quality Review for Virtual Assistant Blog Operations", "month-end blog quality review", "A month-end review should explain how the publishing routine behaved, not merely count how many articles appeared. It looks for repeatable friction, unclear ownership, and evidence that readers received the intended answers.", "Sample completed records, review rework, broken links, recurring exceptions, feedback themes, and delays by cause. Keep operational observations separate from unsupported performance claims and identify one owner for each improvement question.", "A virtual assistant can assemble the evidence pack and trend notes. Editorial leadership decides which process change to test. Do not manufacture a success narrative from volume, and do not publish internal process details in a public article."),
]

images = [
    "virtual-assistant-content-brief-checklist.webp", "virtual-assistant-content-fact-checking.webp", "virtual-assistant-service-quality-assurance.webp", "virtual-assistant-content-calendar-operations.webp", "virtual-assistant-sop-maintenance-controls.webp", "virtual-assistant-content-repurposing-controls.webp", "virtual-assistant-inbox-escalation-matrix.webp", "virtual-assistant-delegation-readiness.webp", "virtual-assistant-social-content-approval.webp", "virtual-assistant-content-approval-workflow.webp", "virtual-assistant-document-version-control.webp", "virtual-assistant-work-sample-review.webp", "virtual-assistant-access-review-cadence.webp", "virtual-assistant-file-naming-convention.webp", "virtual-assistant-content-calendar-workflow.webp", "virtual-assistant-customer-escalation-notes.webp", "virtual-assistant-publishing-calendar-rules.webp", "virtual-assistant-customer-feedback-summary.webp", "virtual-assistant-project-intake-form.webp", "virtual-assistant-content-repurposing-process.webp", "virtual-assistant-sop-writing-guide.webp", "virtual-assistant-service-quality-assurance.webp",
]

entries = []
for i, (slug, title, focus, opening, detail, boundary) in enumerate(topics, 1):
    slug = f"virtual-assistant-aug18-{i:02d}-{slug}"
    title = f"Field Guide: {title}"
    paragraphs = [
        f"{opening} For a company that relies on virtual assistant services to keep daily article creation moving, the practical question is not whether a person can complete an isolated task. It is whether another reviewer can understand the work, verify the important parts, and decide what happens next without guessing.",
        f"Begin by writing down the reader and the operating situation behind {focus}. A useful record names the desired outcome, the source of authority, the deadline or review point, and the information that is deliberately out of scope. This prevents a broad request from quietly becoming a research project, a public promise, or a decision assigned to the wrong role.",
        f"The first pass should preserve context. Record where each important detail came from, when it was checked, and whether it is a confirmed fact, an example, a recommendation, or an unresolved question. {detail} If two sources disagree, keep both visible and state which person must resolve the conflict. Clean-looking notes are not valuable when they conceal uncertainty.",
        f"A second pass should test the handoff. Someone who did not attend the original conversation should be able to identify the current version, the completed work, the open items, and the next owner. Use precise statuses such as waiting for source review, ready for editorial judgment, returned for clarification, or approved for release. Avoid percentages that make progress look precise without explaining evidence.",
        f"The review boundary matters especially in virtual assistant services. {boundary} That boundary protects the business from accidental commitments and protects the assistant from being judged against authority they were never given. Put the boundary in the brief and repeat it in the exception record when a case is unusual.",
        f"When the workflow is working, the record supports a short decision rather than a long reconstruction. The reviewer can see what changed, what was checked, and what remains. If the same question returns repeatedly, improve the instruction or routing rule instead of asking each new assistant to rely on memory. Small improvements in the handoff compound across daily article creation.",
        f"A practical quality check for {focus} asks four questions. Is the reader or internal owner clear? Is the source of truth named? Is uncertainty labeled? Is the next decision assigned to someone with authority? If any answer is no, pause the handoff and fix the record before adding more volume.",
        f"Finally, retain a brief rationale for the decision. A future reviewer may need to know why an item was narrowed, deferred, escalated, or accepted. Keep the rationale factual and proportionate. For {focus}, explain the practical consequence of the choice, the evidence that was available, and the question that would cause the record to be reopened. This makes the note useful even when the original requester is unavailable. The goal is not to create paperwork for its own sake; it is to make a routine dependable when the work moves between people, tools, and review stages. A good record also makes training safer: a new virtual assistant can see the approved pattern, the edge case, and the escalation route without copying a conclusion into a different situation. Review the record for unnecessary personal information, unsupported outcomes, and language that sounds like a guarantee. Remove those before the handoff. Then leave the next owner a concrete action and a date for reconsideration when the matter is still open. It is also worth checking the negative space in the record. What did the process intentionally not collect? Which source was considered but not accepted? Which action remains outside the assistant's authority? Those answers prevent a later reader from mistaking silence for permission. They also help an editor keep public article guidance honest: a workflow can describe a sensible control without claiming that every business uses it or that every issue will disappear. If an example is fictional, label it as an example. If a recommendation depends on context, state the dependency. The resulting article is more useful because its boundaries are visible, and the resulting operating record is easier to review because its purpose is explicit.",
    ]
    body = "\n\n".join(paragraphs)
    sections = [
        (f"{title}: why it needs a defined starting point", paragraphs[1] + "\n\n" + paragraphs[2]),
        ("Build the working record", paragraphs[3] + "\n\n" + paragraphs[4]),
        ("Review, escalate, and close the loop", paragraphs[5] + "\n\n" + paragraphs[6] + "\n\n" + paragraphs[7]),
    ]
    md = ["---", f"slug: {slug}", f"title: {title}", f"excerpt: Practical guidance for {focus} in a reliable virtual assistant services workflow.", f"publishedAt: {DATE}", f"updatedAt: {DATE}", "category: Operations", "tags: [virtual assistant, workflow, operations]", f"featuredImage: /blog/images/{images[i-1]}", f"heroImageAlt: {title}", "readingTime: 9 minutes", "relatedArticles: [virtual-assistant-outsourcing-readiness-checklist, virtual-assistant-content-calendar-operations, virtual-assistant-provider-vetting-checklist]", "---", f"# {title}", "", paragraphs[0]]
    for heading, text in sections:
        md += ["", f"## {heading}", "", text]
    md += ["", "## Practical review questions", "", "Before the item moves forward, confirm the intended reader, evidence boundary, current version, owner, and next decision. A virtual assistant can make each answer visible and flag missing information. The accountable editor or service owner retains the final judgment.", "", "Use the [virtual assistant services library](/services) to compare adjacent support lanes and the [provider vetting guide](/provider-vetting) when defining supervision and backup questions. For a general access baseline, consult the [NIST small business cybersecurity guidance](https://www.nist.gov/itl/smallbusinesscyber).", "", "### What should happen when information is missing?", "", "Label the gap, preserve the source that was checked, and route the decision to the named owner. Do not fill the gap with a plausible assumption.", "", "### When is the handoff complete?", "", "It is complete when the current status, evidence, open questions, and next owner are clear without reconstructing the original request."]
    (BLOG / f"{slug}.mdx").write_text("\n".join(md) + "\n", encoding="utf-8")
    entries.append({"slug": slug, "route": f"/blog/{slug}", "sourcePath": f"content/blog/{slug}.mdx", "sourceDateField": "publishedAt", "sourceDate": DATE, "renderedDate": DATE, "renderedDateFields": ["datePublished", "time[datetime]"], "provenance": "original-aug18-batch", "introducedByCommit": "PENDING"})

manifest = ROOT / ".paperclip/aug18-2026/blog.json"
manifest.parent.mkdir(parents=True, exist_ok=True)
manifest.write_text(json.dumps({"schemaVersion": 1, "contract": "fleet-aug18-blog-v1", "family": "blog", "targetDate": DATE, "minimum": 22, "entries": entries}, indent=2) + "\n", encoding="utf-8")
lengths = [(BLOG / (entry["slug"] + ".mdx")).read_text(encoding="utf-8").split() for entry in entries]
print(f"created {len(entries)} Blog records; shortest body {min(len(words) for words in lengths)} words")
