#!/usr/bin/env python3
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-09-24"
base_source = (ROOT / "scripts" / "create_sep18_research_batch.py").read_text(encoding="utf-8")
namespace = {"__file__": str(ROOT / "scripts" / "create_sep18_research_batch.py")}
exec(base_source.split("\nentries = []", 1)[0], namespace)
namespace["DATE"] = DATE

TOPICS = [
 {"slug":"virtual-assistant-bilingual-support-evidence-study","title":"How Should Buyers Test Bilingual Virtual Assistant Support Claims?","excerpt":"A buyer method for testing language, context, escalation, and review requirements without treating fluency labels as proof.","focus":"bilingual virtual assistant support evidence","question":"how a buyer can test a bilingual support claim for a Filipino virtual assistant role without assuming a fluency label proves task readiness","decision":"whether demonstrated language performance, escalation rules, and review capacity fit the actual customer conversations","unit":"one role-matched language scenario mapped to audience, channel, task, permitted action, prohibited action, rubric, reviewer, and escalation result","scenario":"A provider describes an assistant as bilingual, but the role mixes routine English email with customer calls containing regional expressions, account disputes, and promises that require approval. Conversational fluency alone does not establish listening accuracy, brand-safe writing, or judgment about when to pause.","evidence":"Use paid, role-matched samples across the real channels: a written reply, a call summary, a clarification request, and a stop case. Have qualified reviewers score meaning, tone, completeness, terminology, and escalation separately. Record the language variety and working conditions rather than reducing the result to one fluency label.","limits":"A short sample cannot establish sustained performance, and language varies by region, customer, topic, audio quality, and stress. Reviewer preferences can also be subjective. The test supports a bounded role decision, not a claim that one variety, accent, or communication style is universally better.","finding":"Bilingual support is decision-grade only when the provider demonstrates the exact communication tasks, review standard, and escalation boundary the buyer needs.","image":"/blog/images/virtual-assistant-customer-support-quality-review.webp"},
 {"slug":"virtual-assistant-workload-capacity-evidence-study","title":"What Evidence Shows a Virtual Assistant Has Sustainable Workload Capacity?","excerpt":"A practical framework for comparing promised availability with task volume, queues, interruptions, review, and backup.","focus":"virtual assistant workload capacity evidence","question":"what evidence a buyer should request before relying on a provider's availability or dedicated-capacity claim","decision":"whether the proposed role has enough usable capacity for expected volume, peaks, review, exceptions, and coverage","unit":"one recurring workload mapped to arrival pattern, handling time range, priority, interruption cost, review demand, queue target, owner, and overflow rule","scenario":"A proposal allocates forty weekly hours, while the role includes live inbox coverage, scheduled CRM work, meetings, and unpredictable escalations. Adding estimated task times to forty does not show that time-sensitive work can coexist or that breaks, coaching, rework, and peaks have been allowed for.","evidence":"Build a demand table from a representative period, including low, typical, and peak volumes. Separate scheduled work from queues, record service windows and review time, and run an ordinary week plus a peak scenario. Ask who sees overload first, who reprioritizes, and what backup is actually authorized.","limits":"Historical volume may not predict launches, seasonality, or business change. Handling-time averages can conceal difficult cases, and monitoring can distort behavior. Capacity models should be ranges with explicit assumptions, not promises of continuous maximum utilization.","finding":"Sustainable capacity is a queue-and-priority question, not simply contracted hours; buyers need observable assumptions, overload signals, and recovery ownership.","image":"/blog/images/virtual-assistant-calendar-capacity-review.webp"},
 {"slug":"virtual-assistant-quality-sampling-evidence-study","title":"How Should Buyers Sample Virtual Assistant Work for Quality Review?","excerpt":"A risk-based sampling method that preserves exceptions, reviewer consistency, corrective action, and limits.","focus":"virtual assistant quality sampling evidence","question":"how a buyer can review a useful sample of recurring virtual assistant work without mistaking a small clean set for complete quality assurance","decision":"whether the sampled evidence is sufficient to continue, adjust, or pause a delegated workflow","unit":"one completed work item mapped to risk class, selection rule, required fields, observed defect, reviewer decision, correction, and follow-up result","scenario":"A manager checks the first five completed records each Friday. The sample is easy to administer but can miss late-day work, rare exceptions, and items the assistant already knows will be reviewed. A perfect result therefore says little about the rest of the queue.","evidence":"Combine random items with risk-triggered items, new task types, exceptions, and corrected work. Freeze defect definitions, use a second reviewer on a small calibration set, and preserve denominators. Increase review after meaningful changes or defects, then reduce it only against a documented rule.","limits":"Sampling estimates a process; it does not prove every item is correct. Rare severe errors may require gates or complete review, and reviewer disagreement can be as important as assistant error. Small samples should be reported with uncertainty rather than converted into precise performance claims.","finding":"A useful review sample is selected by a disclosed risk rule and connected to correction and escalation, not chosen only for convenience.","image":"/blog/images/virtual-assistant-article-qa-evidence.webp"},
 {"slug":"virtual-assistant-role-change-control-study","title":"When Should a Virtual Assistant Role Change Trigger Re-Onboarding?","excerpt":"A buyer framework for deciding when new tasks, systems, data, or authority require a fresh readiness review.","focus":"virtual assistant role change control","question":"when a change to a virtual assistant role is material enough to require new instructions, access review, testing, and approval","decision":"whether a proposed change can proceed under the current controls or requires a bounded re-onboarding gate","unit":"one role change mapped to new task, system, data, permission, decision right, volume, schedule, risk, evidence, and approver","scenario":"An assistant hired for CRM cleanup is asked to send customer follow-ups and resolve duplicate records. The new work uses the same platform, but it adds external communication and authority to change customer data. Calling it a minor task extension would hide the changed consequences.","evidence":"Maintain a before-and-after role map. Trigger review when a change adds a system, sensitive data, customer-facing action, financial consequence, approval right, material volume, schedule dependency, or new failure mode. Test ordinary, ambiguous, and stop cases before widening production access.","limits":"No trigger list captures every interaction between small changes. Re-onboarding also consumes time and can become ceremonial if evidence is not role-specific. The accountable owner should document why a change is material or why existing controls remain sufficient.","finding":"Re-onboarding should follow changes in consequence and authority, not just job title; the decision record must show what changed and which evidence supports the wider role.","image":"/blog/images/virtual-assistant-client-onboarding-metrics.webp"},
 {"slug":"virtual-assistant-language-proficiency-review-study","title":"Who Should Review Language Proficiency for a Customer-Facing Virtual Assistant?","excerpt":"A decision framework for matching reviewers, rubrics, customer contexts, and authority to real communication work.","focus":"customer-facing virtual assistant language proficiency review","question":"who is qualified to review language performance for a customer-facing Filipino virtual assistant role and what that reviewer should decide","decision":"whether the reviewer and rubric can judge meaning, task completion, tone, and escalation for the buyer's actual audience","unit":"one communication sample mapped to channel, audience, intent, required facts, prohibited commitment, language variety, rubric, reviewer qualification, and disposition","scenario":"A recruiter scores grammar on a written sample, while the live role requires listening to hurried callers, documenting intent, and avoiding unauthorized commitments. The recruiter can assess part of the work, but the process still lacks a reviewer who understands the customer context and decision boundary.","evidence":"Separate language mechanics from operational judgment. Use a language-capable reviewer for meaning and clarity, a role owner for task accuracy and authority, and a calibrated rubric both can apply. Include accessible call or writing conditions, an ambiguity, and a case that must be escalated.","limits":"Accent familiarity, style preference, and cultural expectations can bias scores. A reviewer who knows the language may not understand the job, while a job expert may miss language nuance. A sample remains a bounded observation and should not be generalized to identity or future performance.","finding":"Customer-facing proficiency needs joint review of language and role judgment, with neither reviewer silently deciding outside their expertise.","image":"/blog/images/virtual-assistant-work-sample-review.webp"}
]

entries=[]
for topic in TOPICS:
    path=ROOT/"content"/"research"/f'{topic["slug"]}.mdx'
    if path.exists(): raise SystemExit(f"refusing to overwrite {path}")
    text=namespace["body"](topic).replace("September 18, 2026","September 24, 2026")
    path.write_text(text,encoding="utf-8")
    entries.append({"family":"research","topic":topic["title"],"slug":topic["slug"],"sourcePaths":[str(path.relative_to(ROOT))],"sourceTitles":[s[0] for s in namespace["SOURCES"]],"sourcePublishers":[s[1] for s in namespace["SOURCES"]],"sources":[s[2] for s in namespace["SOURCES"]],"checkedDate":DATE,"publishedAt":DATE,"contentHash":hashlib.sha256(text.encode()).hexdigest(),"liveUrl":f'https://bestvirtualassistantservices.com/research/{topic["slug"]}',"commitSha":None,"deploymentEvidence":None,"verificationTime":None,"status":"pending-live-verification"})

manifest_path=ROOT/".paperclip"/"daily-content"/DATE/"research.json"
manifest_path.parent.mkdir(parents=True,exist_ok=True)
manifest_path.write_text(json.dumps({"runDate":DATE,"family":"research","requiredCount":5,"verifiedCount":0,"repository":"coolifystealthagents/bestvirtualassistantservices","productionBranch":"main","entries":entries},indent=2)+"\n",encoding="utf-8")
print("created exactly 5 net-new research articles and pending verification manifest")
