export type Alternative = {
  slug: string;
  competitor: string;
  serviceModel: string;
  publishedPrice: string;
  priceNote: string;
  sourceUrl: string;
  bestWhen: string;
  watchFor: string;
  equivalent: string;
  image: string;
};

const raw = [
  ['belay-alternatives','BELAY','US-based fractional support','US-based VAs commonly $1,200 to $3,000 monthly','BELAY describes a customized price shaped by role, hours, and complexity.','https://resources.belaysolutions.com/belay-faq-how-much-does-it-cost-to-hire-a-virtual-assistant-in-the-us','You want US-based fractional executive support and a tailored scope.','A public fixed plan is not offered, so require a written hours and inclusions schedule.','Compare the same monthly hours, assistant location, role seniority, account support, and replacement terms.'],
  ['time-etc-alternatives','Time etc','US-based monthly hour bundle','$390 for 10 hours monthly','The published tiers rise to 60 hours for $2,160, with unused-hour rollover on eligible plans.','https://www.timeetc.com/plans-and-pricing','You need a small, flexible block of experienced US-based assistant time.','An hour bundle is not equivalent to a dedicated full-time assistant.','Compare the same reserved hours, location, rollover, backup cover, manager support, and cancellation terms.'],
  ['prialto-alternatives','Prialto','Managed fractional assistant unit','$1,600 for 55 hours monthly','Prialto also publishes full-time support starting at $3,600 monthly.','https://www.prialto.com/pricing','You value an engagement manager, trained backup, and documented process support.','Confirm the current setup fee, minimum term, and exactly how overflow is handled.','Compare 55 monthly hours plus management, backup coverage, training, security, setup fees, and term length.'],
  ['wing-assistant-alternatives','Wing Assistant','Managed offshore dedicated assistant','$999 for 160 hours monthly','Wing publishes general VA tiers and prices specialty roles separately.','https://get.wingassistant.com/','You want full-time capacity with onboarding, replacement, and a workspace app.','The headline general-assistant plan may not price a specialist or US-based role.','Compare 160 hours, role level, location, supervision, replacement, software, and specialist surcharges.'],
  ['athena-alternatives','Athena','Dedicated full-time executive assistant','$3,000 monthly','Athena publishes one full-time EA, training, equipment, matching, and performance management.','https://www.athena.com/pricing','You want a full-time executive partnership with structured matching and management.','The offering is broader and costlier than a narrow task-based VA plan.','Compare full-time capacity, executive scope, employment model, equipment, training, management, and commitment.'],
  ['zirtual-alternatives','Zirtual','Dedicated US-based hour bundle','$599 for 12 hours monthly','Published plans extend to 45 hours for $1,699 monthly.','https://www.zirtual.com/plans-pricing/','You want a dedicated US-based assistant for a defined monthly workload.','Calculate the effective hourly cost and confirm response and unused-hour policies.','Compare the same hours, user seats, assistant location, dedication, response times, and overage rules.'],
  ['virtual-latinos-alternatives','Virtual Latinos','Managed Latin American talent','Starting at $1,600 monthly','Published ranges vary by experience level and role.','https://www.virtuallatinos.com/pricing/','Bilingual or Latin American market context is important to the role.','Ask for the hours and role level behind the monthly quote before comparing it.','Compare language needs, weekly hours, experience band, recruiting, payroll, replacement, and fees.'],
  ['myoutdesk-alternatives','MyOutDesk','Managed dedicated full-time VA','Starting at $1,988 monthly','MyOutDesk describes managed full-time support, with specialized work priced higher.','https://www.myoutdesk.com/blog/virtual-assistant-cost/','You need a full-time managed assistant and value provider-side HR administration.','Confirm the exact role tier, implementation fee, contract, and included management.','Compare full-time hours, role type, recruiting, HR, oversight, technology, setup, and replacement.'],
  ['woodbows-alternatives','WoodBows','Dedicated weekly hour plan','$99.90 weekly for 10 hours','The published offshore plan lists additional hours separately and no contract.','https://woodbows.com/pricing-previous/','You need a small weekly block and want a dedicated assistant plus account manager.','The cited page is labeled previous, so reconfirm all prices before purchase.','Compare weekly hours, assistant location, experience evidence, manager support, extra-hour cost, and current availability.'],
  ['boldly-alternatives','Boldly','Premium subscription staffing','Quote required','Boldly positions North America and Europe-based subscription staff; current pricing needs sales confirmation.','https://boldly.com/','You need experienced subscription staff in North American or European time zones.','No current public fixed price was found, so the quote must state hours and all fees.','Compare location, reserved hours, seniority, employment model, account support, replacement, and commitment.'],
  ['magic-alternatives','Magic','On-demand and dedicated assistant support','Quote required','Magic offers assistant services, but the current service scope and price should be confirmed in writing.','https://getmagic.com/','You value rapid delegation and want a provider to help route varied requests.','Clarify whether one person or a pool handles work and how sensitive access is controlled.','Compare dedication, hours, response window, location, management, security, and cancellation.'],
  ['fancy-hands-alternatives','Fancy Hands','Shared request-based assistance','Plan price requires current confirmation','Fancy Hands sells requests rather than a reserved block of one dedicated assistant.','https://www.fancyhands.com/','You have small, discrete personal or business requests that do not need continuity.','A request plan is not a fair substitute for recurring process ownership.','Compare request size, response time, shared versus dedicated delivery, revisions, data access, and expiry.'],
  ['wishup-alternatives','Wishup','Managed virtual assistant staffing','Quote required','Wishup markets trained virtual assistants across administrative and specialist tasks.','https://www.wishup.co/','You want provider-led matching and training for a recurring remote role.','Ask for current hours, assistant location, backup, and price because plans can change.','Compare hours, location, role skill, training, account management, backup, and contract terms.'],
  ['taskbullet-alternatives','TaskBullet','Prepaid VA hour bucket','Current bucket price requires confirmation','TaskBullet markets prepaid buckets that can be used without a long-term contract.','https://www.taskbullet.com/','Your workload varies and you prefer a finite bucket over a recurring dedicated hire.','Confirm bucket expiry, staffing continuity, task limits, and the current rate.','Compare usable hours, expiry, assistant continuity, management, permitted work, and refund rules.'],
  ['20four7va-alternatives','20four7VA','Managed virtual staffing','Quote required','20four7VA offers role matching across administrative and specialist support.','https://20four7va.com/','You want a provider to recruit for a clearly scoped remote position.','Require a current quote that separates assistant cost, management, and other fees.','Compare hours, geography, role seniority, recruitment, management, replacement, and total monthly price.'],
  ['remote-coworker-alternatives','Remote CoWorker','Dedicated offshore staffing','Quote required','Remote CoWorker markets dedicated remote staff for full-time and part-time needs.','https://remotecoworker.com/','You need recurring capacity and are prepared to manage a dedicated remote teammate.','Verify current price, work schedule, device standards, supervision, and replacement terms.','Compare reserved hours, location, role level, supervision, equipment, replacement, and contract.'],
  ['virtalent-alternatives','Virtalent','UK-focused managed virtual assistant','Quote required','Virtalent offers UK-based virtual assistants with managed matching.','https://virtalent.com/','UK location and business-hour alignment matter more than the lowest hourly rate.','Ask for the current minimum hours, effective rate, VAT treatment, and cancellation terms.','Compare UK location, hours, seniority, matching, account support, taxes, and flexibility.'],
  ['ossisto-alternatives','Ossisto','Offshore virtual assistant service','Quote required','Ossisto offers administrative, marketing, and specialist virtual support.','https://ossisto.com/','You want a broad task menu and provider-managed offshore support.','A broad capability list is not proof of fit, so run a paid test for the exact workflow.','Compare role-specific evidence, hours, location, manager coverage, security, price, and replacement.'],
] as const;

const images = ['/va-comparison-team.jpg', '/thank-you-hero.png', '/logo.svg'] as const;
export const alternatives: Alternative[] = raw.map((item, index) => ({
  slug:item[0], competitor:item[1], serviceModel:item[2], publishedPrice:item[3], priceNote:item[4],
  sourceUrl:item[5], bestWhen:item[6], watchFor:item[7], equivalent:item[8], image:images[index % images.length],
}));

