import { Header, Footer, CTA, JsonLd } from '../components';
import { site, stats, sourcePlaceholders } from '../data';

export const metadata = { title: 'Virtual assistant pricing guide', description: 'Plain-English virtual assistant pricing ranges, quote questions, and budgeting tips.' };

export default function PricingPage(){
  const schema = { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Virtual assistant pricing guide', url: `${site.url}/pricing`, about: 'Virtual assistant pricing and budgeting' };
  return <><Header/><main className="section"><JsonLd data={schema}/><div className="container"><p className="eyebrow">Pricing</p><h1>Virtual assistant pricing in plain English</h1><p className="lead">Rates change by skill, country, schedule, management support, and risk. Use these ranges as planning numbers, not promises.</p><div className="cards">{stats.map((s)=><div className="card stat" key={s.label}><h3>{s.value}</h3><b>{s.label}</b><p>{s.note}</p></div>)}</div></div><section className="section"><div className="container two"><div><h2>What a quote should include</h2><ul className="list"><li>Hours per week and schedule coverage</li><li>Role type and required tools</li><li>Recruiting, training, and replacement support</li><li>Account management or quality review</li><li>Security rules for passwords and customer data</li></ul></div><div className="card"><h3>Simple monthly math</h3><p>20 hours per week at $10 per hour is about $800 per month before provider fees and tool costs. If a managed service adds support, compare what you get for that extra cost.</p><p>Start with a small pilot so you can test accuracy before increasing hours.</p></div></div></section><section className="section"><div className="container"><h2>Source placeholders</h2><p>These sources give context for wages, hiring, and security planning. Replace or expand them with final editorial citations during deeper research.</p><div className="cards">{sourcePlaceholders.map((s)=><a className="card" href={s.url} key={s.name}><h3>{s.name}</h3><p>{s.note}</p></a>)}</div></div></section><CTA/></main><Footer/></>;
}
